### ISSUE TITLE
Make plane toroidal

### ISSUE THREAD

**Issue by julescarbon** [edwardspeyer/iioiiooiioiooiiiooiioiiooioi#1]
The canvas doesn't loop at the edges, meaning you can get periodic formations with loops that take 3 steps to complete, defeating the state check (line 164) that would otherwise reset the simulation.  I would be remiss not to point out this literal edge condition. Hope you're well!

**Comment by edwardspeyer** [comment]
Thanks for the bug report!

**Comment by edwardspeyer** [comment]
Also: new life randomization with 33b127998cd996e3f0cddf35d6e4d66b66aa73ef; b2bc633ba4ca8d936ed9bebde97319e4ab257fb1

This doesn't solve the reported issue (stale state detection is broken) but it keeps things interesting enough for the animation.

**Comment by edwardspeyer** [comment]
FWIW, I'm not at all convinced the logic for my 2-player GoL is solid either, but when the goal is to dump a bunch of random iiiiiiis and ooooos on screen, this seems to be doing the trick.
